name: QA

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  actionlint:
    name: 'Lint GH Action workflows'
    uses: ./.github/workflows/reusable-actionlint.yml
    with:
      args: '-verbose'
